type ReplacementPair = [RegExp, string];

/** Order: longer/more specific phrases first */
const REPLACEMENTS: ReplacementPair[] = [
  // Measurements
  [/\btablespoons?\b/gi, "बड़ा चम्मच"],
  [/\bteaspoons?\b/gi, "छोटा चम्मच"],
  [/\btbsp\b/gi, "बड़ा चम्मच"],
  [/\btsp\b/gi, "छोटा चम्मच"],
  [/\bcups?\b/gi, "कप"],
  [/\bpinch of\b/gi, "थोड़ी सी"],
  [/\bpinch\b/gi, "चुटकी"],
  [/\bto taste\b/gi, "स्वादानुसार"],
  [/\bfor greasing\b/gi, "चिकना करने के लिए"],
  [/\bfor serving\b/gi, "परोसने के लिए"],
  [/\bfor frying\b/gi, "तलने के लिए"],
  [/\bfor garnish(?:ing)?\b/gi, "सजाने के लिए"],

  // Ingredients — longer/more specific first
  [/\bwhole wheat flour\b/gi, "पूरे गेहूं का आटा"],
  [/\ball-purpose flour\b/gi, "मैदा"],
  [/\bwheat flour\b/gi, "गेहूं का आटा"],
  [/\brice flour\b/gi, "चावल का आटा"],
  [/\bchickpea flour\b/gi, "बेसन"],
  [/\bflour\b/gi, "आटा"],
  [/\bparboiled rice\b/gi, "उबला चावल"],
  [/\bbasmati rice\b/gi, "बासमती चावल"],
  [/\brice\b/gi, "चावल"],
  [/\bmustard oil\b/gi, "सरसों का तेल"],
  [/\bcoconut oil\b/gi, "नारियल का तेल"],
  [/\bvegetable oil\b/gi, "तेल"],
  [/\boil\b/gi, "तेल"],
  [/\bghee\b/gi, "घी"],
  [/\bbutter\b/gi, "मक्खन"],
  [/\bcream\b/gi, "मलाई"],
  [/\byogurt\b/gi, "दही"],
  [/\bcurd\b/gi, "दही"],
  [/\bcondensed milk\b/gi, "कंडेंस्ड दूध"],
  [/\bcoconut milk\b/gi, "नारियल का दूध"],
  [/\bmilk\b/gi, "दूध"],
  [/\bcottage cheese\b/gi, "पनीर"],
  [/\bpaneer\b/gi, "पनीर"],
  [/\bkhoya\b/gi, "खोया"],
  [/\bmawa\b/gi, "खोया"],
  [/\brabri\b/gi, "रबड़ी"],
  [/\bmalai\b/gi, "मलाई"],
  [/\bspring onions?\b/gi, "हरा प्याज"],
  [/\bonions?\b/gi, "प्याज"],
  [/\bgarlic\b/gi, "लहसुन"],
  [/\bginger\b/gi, "अदरक"],
  [/\btomatoes?\b/gi, "टमाटर"],
  [/\bpotatoes?\b/gi, "आलू"],
  [/\bspinach\b/gi, "पालक"],
  [/\bcauliflower\b/gi, "गोभी"],
  [/\bgreen peas\b/gi, "हरी मटर"],
  [/\bpeas\b/gi, "मटर"],
  [/\bcarrots?\b/gi, "गाजर"],
  [/\bcapsicum\b/gi, "शिमला मिर्च"],
  [/\bbell pepper\b/gi, "शिमला मिर्च"],
  [/\beggplant\b/gi, "बैंगन"],
  [/\bbrinjal\b/gi, "बैंगन"],
  [/\bbottle gourd\b/gi, "लौकी"],
  [/\bbitter gourd\b/gi, "करेला"],
  [/\bdrumstick\b/gi, "सहजन"],
  [/\braw mango\b/gi, "कच्चा आम"],
  [/\braw banana\b/gi, "कच्चा केला"],
  [/\bbanana\b/gi, "केला"],
  [/\bmango\b/gi, "आम"],
  [/\bapple\b/gi, "सेब"],
  [/\borange\b/gi, "संतरा"],
  [/\bpomegranate\b/gi, "अनार"],
  [/\bpineapple\b/gi, "अनानास"],
  [/\bgrapes\b/gi, "अंगूर"],
  [/\bwatermelon\b/gi, "तरबूज"],
  [/\bpapaya\b/gi, "पपीता"],
  [/\bcoriander leaves\b/gi, "हरा धनिया"],
  [/\bmint leaves\b/gi, "पुदीना"],
  [/\bmint\b/gi, "पुदीना"],
  [/\bfenugreek seeds\b/gi, "मेथी के बीज"],
  [/\bdry fenugreek\b/gi, "कसूरी मेथी"],
  [/\bkasuri methi\b/gi, "कसूरी मेथी"],
  [/\bfenugreek\b/gi, "मेथी"],
  [/\bmustard seeds\b/gi, "राई"],
  [/\bcumin seeds\b/gi, "जीरा"],
  [/\bcoriander powder\b/gi, "धनिया पाउडर"],
  [/\bcoriander\b/gi, "धनिया"],
  [/\bturmeric powder\b/gi, "हल्दी"],
  [/\bturmeric\b/gi, "हल्दी"],
  [/\bred chilli powder\b/gi, "लाल मिर्च पाउडर"],
  [/\bchilli powder\b/gi, "लाल मिर्च पाउडर"],
  [/\bgreen chilli(?:es)?\b/gi, "हरी मिर्च"],
  [/\bdry red chilli(?:es)?\b/gi, "सूखी लाल मिर्च"],
  [/\bkashmiri chilli\b/gi, "कश्मीरी मिर्च"],
  [/\bred chilli(?:es)?\b/gi, "लाल मिर्च"],
  [/\bblack pepper\b/gi, "काली मिर्च"],
  [/\bblack cardamom\b/gi, "बड़ी इलायची"],
  [/\bcardamom powder\b/gi, "इलायची पाउडर"],
  [/\bcardamom\b/gi, "इलायची"],
  [/\bcinnamon\b/gi, "दालचीनी"],
  [/\bcloves?\b/gi, "लौंग"],
  [/\bstar anise\b/gi, "चक्री फूल"],
  [/\bbay leaves?\b/gi, "तेज पत्ता"],
  [/\basafoetida\b/gi, "हींग"],
  [/\bcurry leaves?\b/gi, "करी पत्ता"],
  [/\bsaffron\b/gi, "केसर"],
  [/\bgaram masala\b/gi, "गरम मसाला"],
  [/\bchaat masala\b/gi, "चाट मसाला"],
  [/\bamchur\b/gi, "अमचूर"],
  [/\bdried mango powder\b/gi, "अमचूर"],
  [/\bmace\b/gi, "जावित्री"],
  [/\bnutmeg\b/gi, "जायफल"],
  [/\bfennel seeds\b/gi, "सौंफ"],
  [/\bcarom seeds\b/gi, "अजवाइन"],
  [/\bnigella seeds\b/gi, "कलौंजी"],
  [/\bpoppy seeds\b/gi, "खस खस"],
  [/\bcumin powder\b/gi, "जीरा पाउडर"],
  [/\bcumin\b/gi, "जीरा"],
  [/\bblack salt\b/gi, "काला नमक"],
  [/\brock salt\b/gi, "सेंधा नमक"],
  [/\bsalt\b/gi, "नमक"],
  [/\bwhite sugar\b/gi, "सफेद चीनी"],
  [/\bbrown sugar\b/gi, "ब्राउन शुगर"],
  [/\bpowdered sugar\b/gi, "पिसी चीनी"],
  [/\bsugar\b/gi, "चीनी"],
  [/\bjaggery\b/gi, "गुड़"],
  [/\bhoney\b/gi, "शहद"],
  [/\blemon juice\b/gi, "नींबू का रस"],
  [/\blime juice\b/gi, "नींबू का रस"],
  [/\blemons?\b/gi, "नींबू"],
  [/\bwater\b/gi, "पानी"],
  [/\bcoconut\b/gi, "नारियल"],
  [/\btamarind\b/gi, "इमली"],
  [/\bvinegar\b/gi, "सिरका"],
  [/\burad dal\b/gi, "उड़द दाल"],
  [/\bchana dal\b/gi, "चना दाल"],
  [/\bmoong dal\b/gi, "मूंग दाल"],
  [/\btoor dal\b/gi, "तूर दाल"],
  [/\bkabuli chana\b/gi, "काबुली चना"],
  [/\blentils\b/gi, "दाल"],
  [/\bchickpeas?\b/gi, "छोले"],
  [/\bkidney beans\b/gi, "राजमा"],
  [/\brajma\b/gi, "राजमा"],
  [/\bmoong\b/gi, "मूंग"],
  [/\bchicken\b/gi, "मुर्गा"],
  [/\bmutton\b/gi, "मटन"],
  [/\blamb\b/gi, "मटन"],
  [/\bfish\b/gi, "मछली"],
  [/\bprawns?\b/gi, "झींगा"],
  [/\bshrimp\b/gi, "झींगा"],
  [/\bcrab\b/gi, "केकड़ा"],
  [/\beggs?\b/gi, "अंडा"],
  [/\bsemolina\b/gi, "सूजी"],
  [/\brava\b/gi, "सूजी"],
  [/\bflattened rice\b/gi, "पोहा"],
  [/\bpuffed rice\b/gi, "मुरमुरे"],
  [/\bbread crumbs\b/gi, "ब्रेड के टुकड़े"],
  [/\bcorn\b/gi, "मक्का"],
  [/\bvermicelli\b/gi, "सेवइयां"],
  [/\bbaking soda\b/gi, "मीठा सोडा"],
  [/\btomato paste\b/gi, "टमाटर पेस्ट"],
  [/\btomato puree\b/gi, "टमाटर प्यूरी"],
  [/\bcashews?\b/gi, "काजू"],
  [/\balmonds?\b/gi, "बादाम"],
  [/\bpistachios?\b/gi, "पिस्ता"],
  [/\braisins?\b/gi, "किशमिश"],
  [/\bpeanuts?\b/gi, "मूंगफली"],
  [/\bsesame seeds\b/gi, "तिल"],
  [/\bwalnut\b/gi, "अखरोट"],
  [/\brose water\b/gi, "गुलाब जल"],
  [/\btea\b/gi, "चाय"],
  [/\bice\b/gi, "बर्फ"],
  [/\bradish\b/gi, "मूली"],
  [/\bbeetroot\b/gi, "चुकंदर"],
  [/\bcucumber\b/gi, "खीरा"],
  [/\bpumpkin\b/gi, "कद्दू"],
  [/\bmushroom\b/gi, "मशरूम"],
  [/\bbasil\b/gi, "तुलसी"],
  [/\btulsi\b/gi, "तुलसी"],
  [/\bbesan\b/gi, "बेसन"],

  // Cooking instructions
  [/\bpressure cook\b/gi, "कुकर में पकाएं"],
  [/\bdeep fry\b/gi, "डीप फ्राई करें"],
  [/\bshallow fry\b/gi, "थोड़े तेल में तलें"],
  [/\bstir fry\b/gi, "कड़ाही में भूनें"],
  [/\bpan fry\b/gi, "कड़ाही में तलें"],
  [/\bdry roast\b/gi, "सूखा भूनें"],
  [/\bheat the oil\b/gi, "तेल गरम करें"],
  [/\bheat oil\b/gi, "तेल गरम करें"],
  [/\bbring to boil\b/gi, "उबाल आने दें"],
  [/\breduce heat\b/gi, "आंच कम करें"],
  [/\bincrease heat\b/gi, "आंच बढ़ाएं"],
  [/\bcool completely\b/gi, "पूरी तरह ठंडा करें"],
  [/\blet it cool\b/gi, "ठंडा होने दें"],
  [/\bmix well\b/gi, "अच्छे से मिलाएं"],
  [/\bheat\b/gi, "गरम करें"],
  [/\bsoaked\b/gi, "भिगोया हुआ"],
  [/\bsoak\b/gi, "भिगो दें"],
  [/\bgrind\b/gi, "पीस लें"],
  [/\bblend\b/gi, "ब्लेंड करें"],
  [/\bferment\b/gi, "खमीर उठने दें"],
  [/\bknead well\b/gi, "अच्छे से गूंधें"],
  [/\bknead into a dough\b/gi, "आटा गूंधें"],
  [/\bknead\b/gi, "गूंधें"],
  [/\bboiled\b/gi, "उबला हुआ"],
  [/\bboil\b/gi, "उबालें"],
  [/\bsimmer\b/gi, "धीमी आंच पर पकाएं"],
  [/\bfry\b/gi, "तलें"],
  [/\bsaute\b/gi, "भूनें"],
  [/\broasted\b/gi, "भूनें"],
  [/\broast\b/gi, "भूनें"],
  [/\btoast\b/gi, "टोस्ट करें"],
  [/\bbake\b/gi, "बेक करें"],
  [/\bsteam\b/gi, "भाप में पकाएं"],
  [/\bgrill\b/gi, "ग्रिल करें"],
  [/\bcooked\b/gi, "पकाएं"],
  [/\bcook\b/gi, "पकाएं"],
  [/\bmash\b/gi, "मसल दें"],
  [/\bcrush\b/gi, "कुचल दें"],
  [/\btemper\b/gi, "तड़का लगाएं"],
  [/\bstir\b/gi, "हिलाएं"],
  [/\bmix\b/gi, "मिलाएं"],
  [/\badd\b/gi, "डालें"],
  [/\bpour\b/gi, "डालें"],
  [/\bsprinkle\b/gi, "छिड़कें"],
  [/\bchopped\b/gi, "कटा हुआ"],
  [/\bchop\b/gi, "काट लें"],
  [/\bsliced\b/gi, "स्लाइस किया हुआ"],
  [/\bslice\b/gi, "स्लाइस करें"],
  [/\bgrated\b/gi, "कद्दूकस किया हुआ"],
  [/\bgrate\b/gi, "कद्दूकस करें"],
  [/\bpeeled\b/gi, "छीला हुआ"],
  [/\bpeel\b/gi, "छील लें"],
  [/\bdrain\b/gi, "पानी निकालें"],
  [/\bwash\b/gi, "धो लें"],
  [/\brinse\b/gi, "धो लें"],
  [/\bmarinated\b/gi, "मेरीनेट करें"],
  [/\bmarinate\b/gi, "मेरीनेट करें"],
  [/\bgarnish\b/gi, "सजाएं"],
  [/\bserve\b/gi, "परोसें"],
  [/\bcover\b/gi, "ढक दें"],
  [/\bset aside\b/gi, "अलग रख दें"],
  [/\bstrain\b/gi, "छान लें"],
  [/\bfilter\b/gi, "छानें"],
  [/\bremove\b/gi, "निकालें"],
  [/\broll\b/gi, "बेल लें"],
  [/\bspread\b/gi, "फैलाएं"],
  [/\bfold\b/gi, "मोड़ लें"],
  [/\bpress\b/gi, "दबाएं"],
  [/\bwhisk\b/gi, "फेंटें"],
  [/\bbeat\b/gi, "फेंटें"],
  [/\btoss\b/gi, "उछाल कर मिलाएं"],
  [/\bflip\b/gi, "पलटें"],
  [/\bturn\b/gi, "पलटें"],
  [/\bsqueeze\b/gi, "निचोड़ लें"],
  [/\bdissolve\b/gi, "घोल दें"],
  [/\brefrigerate\b/gi, "फ्रिज में रख दें"],
  [/\bfreeze\b/gi, "फ्रीज करें"],
  [/\bthicken\b/gi, "गाढ़ा करें"],
  [/\breduce\b/gi, "गाढ़ा करें"],
  [/\brest\b/gi, "आराम करने दें"],
  [/\bcool\b/gi, "ठंडा करें"],

  // Common phrases
  [/\buntil golden brown\b/gi, "सुनहरे रंग तक"],
  [/\buntil golden\b/gi, "सुनहरे रंग तक"],
  [/\buntil tender\b/gi, "नरम होने तक"],
  [/\buntil soft\b/gi, "नरम होने तक"],
  [/\buntil fragrant\b/gi, "खुशबू आने तक"],
  [/\buntil done\b/gi, "पकने तक"],
  [/\buntil thick\b/gi, "गाढ़ा होने तक"],
  [/\buntil oil separates\b/gi, "तेल अलग होने तक"],
  [/\bover medium heat\b/gi, "मध्यम आंच पर"],
  [/\bin a blender\b/gi, "मिक्सर में"],
  [/\bin a pan\b/gi, "कड़ाही में"],
  [/\bin a pot\b/gi, "पतीले में"],
  [/\bin a bowl\b/gi, "कटोरे में"],
  [/\bon a tawa\b/gi, "तवे पर"],
  [/\bhigh heat\b/gi, "तेज आंच"],
  [/\bmedium heat\b/gi, "मध्यम आंच"],
  [/\blow heat\b/gi, "धीमी आंच"],
  [/\bovernight\b/gi, "रात भर के लिए"],
  [/\bmeanwhile\b/gi, "तब तक"],
  [/\bfinally\b/gi, "आखिर में"],
  [/\bfirst\b/gi, "पहले"],
  [/\bthen\b/gi, "फिर"],
  [/\boptional\b/gi, "वैकल्पिक"],
  [/\baccording to taste\b/gi, "स्वादानुसार"],
  [/\bas needed\b/gi, "जरूरत अनुसार"],
  [/\bhours?\b/gi, "घंटे"],
  [/\bminutes?\b/gi, "मिनट"],
  [/\bseparately\b/gi, "अलग अलग"],
  [/\bthoroughly\b/gi, "अच्छे से"],
  [/\bgently\b/gi, "धीरे से"],
  [/\bslowly\b/gi, "धीरे धीरे"],
  [/\bimmediately\b/gi, "तुरंत"],
  [/\bfinely\b/gi, "बारीक"],
  [/\broughly\b/gi, "मोटा मोटा"],
  [/\bfresh\b/gi, "ताजा"],
  [/\bdry\b/gi, "सूखा"],
  [/\braw\b/gi, "कच्चा"],
  [/\bripe\b/gi, "पका हुआ"],
  [/\bthick\b/gi, "गाढ़ा"],
  [/\bthin\b/gi, "पतला"],
  [/\bcrispy\b/gi, "कुरकुरा"],
  [/\bcrunchy\b/gi, "कुरकुरा"],
  [/\bsoft\b/gi, "नरम"],
  [/\bspicy\b/gi, "तीखा"],
  [/\bmild\b/gi, "हल्का"],
  [/\btangy\b/gi, "खट्टा"],
  [/\bsweet\b/gi, "मीठा"],
  [/\bsalty\b/gi, "नमकीन"],
  [/\bbitter\b/gi, "कड़वा"],
  [/\bhot\b/gi, "गरम"],
  [/\bwarm\b/gi, "गुनगुना"],
  [/\blarge\b/gi, "बड़ा"],
  [/\bsmall\b/gi, "छोटा"],
  [/\bmedium\b/gi, "मध्यम"],
];

export function toHindi(text: string): string {
  let result = text;
  for (const [pattern, replacement] of REPLACEMENTS) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

export function toHindiList(items: string[]): string[] {
  return items.map(toHindi);
}
