type ReplacementPair = [RegExp, string];

/** Order: longer/more specific phrases first */
const REPLACEMENTS: ReplacementPair[] = [
  // Measurements
  [/\btablespoons?\b/gi, "bade chamach"],
  [/\bteaspoons?\b/gi, "chote chamach"],
  [/\btbsp\b/gi, "bada chamach"],
  [/\btsp\b/gi, "chota chamach"],
  [/\bcups?\b/gi, "cup"],
  [/\bpinch of\b/gi, "thodi si"],
  [/\bpinch\b/gi, "chutki"],
  [/\bto taste\b/gi, "swad anusar"],
  [/\bfor greasing\b/gi, "grease karne ke liye"],
  [/\bfor serving\b/gi, "serve karne ke liye"],
  [/\bfor frying\b/gi, "fry karne ke liye"],
  [/\bfor garnish(?:ing)?\b/gi, "garnish ke liye"],

  // Ingredients — longer/more specific first
  [/\bwhole wheat flour\b/gi, "gehun ka atta"],
  [/\ball-purpose flour\b/gi, "maida"],
  [/\bwheat flour\b/gi, "gehun ka atta"],
  [/\brice flour\b/gi, "chawal ka atta"],
  [/\bflour\b/gi, "atta"],
  [/\bparboiled rice\b/gi, "ubla hua chawal"],
  [/\bbasmati rice\b/gi, "basmati chawal"],
  [/\brice\b/gi, "chawal"],
  [/\bmustard oil\b/gi, "sarson ka tel"],
  [/\bcoconut oil\b/gi, "nariyal ka tel"],
  [/\bvegetable oil\b/gi, "tel"],
  [/\boil\b/gi, "tel"],
  [/\bghee\b/gi, "ghee"],
  [/\bbutter\b/gi, "makkhan"],
  [/\bcream\b/gi, "malai"],
  [/\byogurt\b/gi, "dahi"],
  [/\bcurd\b/gi, "dahi"],
  [/\bmilk\b/gi, "doodh"],
  [/\bcottage cheese\b/gi, "paneer"],
  [/\bpaneer\b/gi, "paneer"],
  [/\bonions?\b/gi, "pyaaz"],
  [/\bgarlic\b/gi, "lahsun"],
  [/\bginger\b/gi, "adrak"],
  [/\btomatoes?\b/gi, "tamatar"],
  [/\bpotatoes?\b/gi, "aloo"],
  [/\bspinach\b/gi, "palak"],
  [/\bcauliflower\b/gi, "gobi"],
  [/\bgreen peas\b/gi, "hari matar"],
  [/\bpeas\b/gi, "matar"],
  [/\bcarrots?\b/gi, "gajar"],
  [/\bcapsicum\b/gi, "shimla mirch"],
  [/\bbell pepper\b/gi, "shimla mirch"],
  [/\beggplant\b/gi, "baingan"],
  [/\bbrinjal\b/gi, "baingan"],
  [/\bfenugreek seeds?\b/gi, "methi ke beej"],
  [/\bfenugreek\b/gi, "methi"],
  [/\bmustard seeds?\b/gi, "rai"],
  [/\bcumin seeds?\b/gi, "jeera"],
  [/\bcumin\b/gi, "jeera"],
  [/\bcoriander powder\b/gi, "dhaniya powder"],
  [/\bcoriander\b/gi, "dhaniya"],
  [/\bturmeric powder\b/gi, "haldi"],
  [/\bturmeric\b/gi, "haldi"],
  [/\bred chilli? powder\b/gi, "lal mirch powder"],
  [/\bchilli? powder\b/gi, "mirch powder"],
  [/\bgreen chilli?(?:es)?\b/gi, "hari mirch"],
  [/\bred chilli?(?:es)?\b/gi, "lal mirch"],
  [/\bblack pepper\b/gi, "kali mirch"],
  [/\bcardamom\b/gi, "elaichi"],
  [/\bcinnamon\b/gi, "dalchini"],
  [/\bcloves?\b/gi, "laung"],
  [/\bstar anise\b/gi, "chakri phool"],
  [/\bbay leaves?\b/gi, "tej patta"],
  [/\basafoetida\b/gi, "hing"],
  [/\bcurry leaves?\b/gi, "curry patta"],
  [/\bsaffron\b/gi, "kesar"],
  [/\bgaram masala\b/gi, "garam masala"],
  [/\bsalt\b/gi, "namak"],
  [/\bsugar\b/gi, "cheeni"],
  [/\bjaggery\b/gi, "gur"],
  [/\bhoney\b/gi, "shahad"],
  [/\blemon juice\b/gi, "nimbu ka ras"],
  [/\blime juice\b/gi, "nimbu ka ras"],
  [/\blemons?\b/gi, "nimbu"],
  [/\bwater\b/gi, "paani"],
  [/\bcoconut milk\b/gi, "nariyal ka doodh"],
  [/\bcoconut\b/gi, "nariyal"],
  [/\btamarind\b/gi, "imli"],
  [/\bvinegar\b/gi, "sirka"],
  [/\burad dal\b/gi, "urad dal"],
  [/\bchana dal\b/gi, "chana dal"],
  [/\bmoong dal\b/gi, "moong dal"],
  [/\btoor dal\b/gi, "toor dal"],
  [/\blentils\b/gi, "dal"],
  [/\bchickpeas?\b/gi, "chhole"],
  [/\bkidney beans\b/gi, "rajma"],
  [/\bchicken\b/gi, "murga"],
  [/\bmutton\b/gi, "gosht"],
  [/\bfish\b/gi, "machli"],
  [/\bprawns?\b/gi, "jheenga"],
  [/\bshrimp\b/gi, "jheenga"],
  [/\beggs?\b/gi, "anda"],
  [/\bsemolina\b/gi, "sooji"],
  [/\brava\b/gi, "sooji"],
  [/\bbaking soda\b/gi, "meetha soda"],
  [/\btomato paste\b/gi, "tamatar paste"],
  [/\btomato puree\b/gi, "tamatar puree"],
  [/\bcashews?\b/gi, "kaju"],
  [/\balmonds?\b/gi, "badam"],
  [/\bpistachios?\b/gi, "pista"],
  [/\braisins?\b/gi, "kishmish"],
  [/\bpeanuts?\b/gi, "moongfali"],
  [/\bsesame seeds?\b/gi, "til"],
  [/\brose water\b/gi, "gulab jal"],
  [/\bice\b/gi, "barf"],

  // Cooking instructions — longer phrases first
  [/\bheat the oil\b/gi, "tel garam karo"],
  [/\bheat oil\b/gi, "tel garam karo"],
  [/\bheat\b/gi, "garam karo"],
  [/\bsoaked\b/gi, "bhiga hua"],
  [/\bsoak\b/gi, "bhigo do"],
  [/\bgrind\b/gi, "pees lo"],
  [/\bblend\b/gi, "blend karo"],
  [/\bfermented\b/gi, "khameer uthi hui"],
  [/\bferment\b/gi, "khameer uthne do"],
  [/\bknead\b/gi, "goondo"],
  [/\bboiled\b/gi, "ubla hua"],
  [/\bboil\b/gi, "ubalo"],
  [/\bsimmer\b/gi, "dhimi aanch par pakao"],
  [/\bdeep[- ]fry\b/gi, "deep fry karo"],
  [/\bshallow fry\b/gi, "thode tel mein talo"],
  [/\bstir[- ]fry\b/gi, "kadhai mein fry karo"],
  [/\bfried\b/gi, "fry kiya hua"],
  [/\bfry\b/gi, "fry karo"],
  [/\bsaut[eé]\b/gi, "saute karo"],
  [/\broasted\b/gi, "bhuney hue"],
  [/\broast\b/gi, "bhuno"],
  [/\bbake\b/gi, "bake karo"],
  [/\bsteamed\b/gi, "bhap mein paka hua"],
  [/\bsteam\b/gi, "bhap mein pakao"],
  [/\bpressure[- ]cook\b/gi, "cooker mein pakao"],
  [/\bcooked\b/gi, "paka hua"],
  [/\bcook\b/gi, "pakao"],
  [/\bstir\b/gi, "hilao"],
  [/\bmix well\b/gi, "achhe se mix karo"],
  [/\bmix\b/gi, "mix karo"],
  [/\badd\b/gi, "dalo"],
  [/\bpour\b/gi, "daalo"],
  [/\bsprinkle\b/gi, "chidko"],
  [/\bchopped\b/gi, "kata hua"],
  [/\bchop\b/gi, "kaat lo"],
  [/\bsliced\b/gi, "slice kiya hua"],
  [/\bslice\b/gi, "slice karo"],
  [/\bgrated\b/gi, "kada hua"],
  [/\bgrate\b/gi, "kado lo"],
  [/\bpeeled\b/gi, "chheela hua"],
  [/\bpeel\b/gi, "chheel lo"],
  [/\bdrain\b/gi, "paani nikaalo"],
  [/\bwash\b/gi, "dho lo"],
  [/\brinse\b/gi, "dho lo"],
  [/\bmarinated\b/gi, "marinate kiya hua"],
  [/\bmarinate\b/gi, "marinate karo"],
  [/\bgarnish\b/gi, "garnish karo"],
  [/\bserve\b/gi, "serve karo"],
  [/\bcover\b/gi, "dhak do"],
  [/\blet it cool\b/gi, "thanda hone do"],
  [/\bcool\b/gi, "thanda karo"],
  [/\bset aside\b/gi, "alag rakh do"],
  [/\bstrain\b/gi, "chhaan lo"],
  [/\bremove\b/gi, "nikaalo"],
  [/\brolled\b/gi, "bela hua"],
  [/\broll\b/gi, "bel lo"],
  [/\bspread\b/gi, "failao"],
  [/\bfold\b/gi, "mod lo"],
  [/\bpress\b/gi, "dabaao"],
  [/\bwhisk\b/gi, "phento"],
  [/\bbeat\b/gi, "phento"],

  // Common phrases
  [/\buntil golden brown\b/gi, "sone ke rang tak"],
  [/\buntil golden\b/gi, "sone ke rang tak"],
  [/\buntil tender\b/gi, "naram hone tak"],
  [/\buntil soft\b/gi, "naram hone tak"],
  [/\buntil fragrant\b/gi, "khusboo aane tak"],
  [/\buntil done\b/gi, "pakne tak"],
  [/\buntil thick\b/gi, "gaadha hone tak"],
  [/\bhigh heat\b/gi, "tej aanch"],
  [/\bmedium heat\b/gi, "madhyam aanch"],
  [/\blow heat\b/gi, "dhimi aanch"],
  [/\bovernight\b/gi, "raat bhar ke liye"],
  [/\bminutes?\b/gi, "minute"],
  [/\bhours?\b/gi, "ghante"],
  [/\bseparately\b/gi, "alag alag"],
  [/\bthoroughly\b/gi, "achhe se"],
  [/\bgently\b/gi, "dheere se"],
  [/\bslowly\b/gi, "dheere dheere"],
  [/\bimmediately\b/gi, "turant"],
];

export function toHinglish(text: string): string {
  let result = text;
  for (const [pattern, replacement] of REPLACEMENTS) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

export function toHinglishList(items: string[]): string[] {
  return items.map(toHinglish);
}
