type ReplacementPair = [RegExp, string];

/** Order: longer/more specific phrases first */
const REPLACEMENTS: ReplacementPair[] = [
  // Measurements
  [/\btablespoons?\b/gi, "bade chamach"],
  [/\bteaspoons?\b/gi, "chote chamach"],
  [/\btbsp\b/gi, "bada chamach"],
  [/\btsp\b/gi, "chota chamach"],
  [/\bcups?\b/gi, "cup"],
  [/\bpinch of\b/gi, "thodi si"],
  [/\bpinch\b/gi, "chutki"],
  [/\bto taste\b/gi, "swad anusar"],
  [/\bfor greasing\b/gi, "grease karne ke liye"],
  [/\bfor serving\b/gi, "serve karne ke liye"],
  [/\bfor frying\b/gi, "fry karne ke liye"],
  [/\bfor garnish(?:ing)?\b/gi, "garnish ke liye"],

  // Ingredients — longer/more specific first
  [/\bwhole wheat flour\b/gi, "gehun ka atta"],
  [/\ball-purpose flour\b/gi, "maida"],
  [/\bwheat flour\b/gi, "gehun ka atta"],
  [/\brice flour\b/gi, "chawal ka atta"],
  [/\bchickpea flour\b/gi, "besan"],
  [/\bflour\b/gi, "atta"],
  [/\bparboiled rice\b/gi, "ubla hua chawal"],
  [/\bbasmati rice\b/gi, "basmati chawal"],
  [/\brice\b/gi, "chawal"],
  [/\bmustard oil\b/gi, "sarson ka tel"],
  [/\bcoconut oil\b/gi, "nariyal ka tel"],
  [/\bvegetable oil\b/gi, "tel"],
  [/\boil\b/gi, "tel"],
  [/\bghee\b/gi, "ghee"],
  [/\bbutter\b/gi, "makkhan"],
  [/\bcream\b/gi, "malai"],
  [/\byogurt\b/gi, "dahi"],
  [/\bcurd\b/gi, "dahi"],
  [/\bcondensed milk\b/gi, "condensed doodh"],
  [/\bcoconut milk\b/gi, "nariyal ka doodh"],
  [/\bmilk\b/gi, "doodh"],
  [/\bcottage cheese\b/gi, "paneer"],
  [/\bpaneer\b/gi, "paneer"],
  [/\bkhoya\b/gi, "khoya"],
  [/\bmawa\b/gi, "khoya"],
  [/\brabri\b/gi, "rabri"],
  [/\bmalai\b/gi, "malai"],
  [/\bonions?\b/gi, "pyaaz"],
  [/\bspring onions?\b/gi, "hara pyaaz"],
  [/\bgarlic\b/gi, "lahsun"],
  [/\bginger\b/gi, "adrak"],
  [/\btomatoes?\b/gi, "tamatar"],
  [/\bpotatoes?\b/gi, "aloo"],
  [/\bspinach\b/gi, "palak"],
  [/\bcauliflower\b/gi, "gobi"],
  [/\bgreen peas\b/gi, "hari matar"],
  [/\bpeas\b/gi, "matar"],
  [/\bcarrots?\b/gi, "gajar"],
  [/\bcapsicum\b/gi, "shimla mirch"],
  [/\bbell pepper\b/gi, "shimla mirch"],
  [/\beggplant\b/gi, "baingan"],
  [/\bbrinjal\b/gi, "baingan"],
  [/\bbottle gourd\b/gi, "lauki"],
  [/\bbitter gourd\b/gi, "karela"],
  [/\bridge gourd\b/gi, "tori"],
  [/\bdrumstick\b/gi, "sahjan"],
  [/\braw mango\b/gi, "kaccha aam"],
  [/\braw banana\b/gi, "kaccha kela"],
  [/\bbanana\b/gi, "kela"],
  [/\bmango\b/gi, "aam"],
  [/\bapple\b/gi, "seb"],
  [/\borange\b/gi, "santra"],
  [/\bpomegranate\b/gi, "anar"],
  [/\bpineapple\b/gi, "ananas"],
  [/\bgrapes\b/gi, "angur"],
  [/\bwatermelon\b/gi, "tarbooz"],
  [/\bpapaya\b/gi, "papita"],
  [/\bcoriander leaves\b/gi, "hara dhaniya"],
  [/\bmint leaves\b/gi, "pudina"],
  [/\bmint\b/gi, "pudina"],
  [/\bfenugreek seeds?\b/gi, "methi ke beej"],
  [/\bdry fenugreek\b/gi, "kasuri methi"],
  [/\bkasuri methi\b/gi, "kasuri methi"],
  [/\bfenugreek\b/gi, "methi"],
  [/\bmustard seeds?\b/gi, "rai"],
  [/\bcumin seeds?\b/gi, "jeera"],
  [/\bcumin\b/gi, "jeera"],
  [/\bcoriander powder\b/gi, "dhaniya powder"],
  [/\bcoriander\b/gi, "dhaniya"],
  [/\bturmeric powder\b/gi, "haldi"],
  [/\bturmeric\b/gi, "haldi"],
  [/\bred chilli? powder\b/gi, "lal mirch powder"],
  [/\bchilli? powder\b/gi, "mirch powder"],
  [/\bgreen chilli?(?:es)?\b/gi, "hari mirch"],
  [/\bdry red chilli?(?:es)?\b/gi, "sukhi lal mirch"],
  [/\bkashmiri chilli?\b/gi, "kashmiri mirch"],
  [/\bred chilli?(?:es)?\b/gi, "lal mirch"],
  [/\bblack pepper\b/gi, "kali mirch"],
  [/\bblack cardamom\b/gi, "badi elaichi"],
  [/\bcardamom powder\b/gi, "elaichi powder"],
  [/\bcardamom\b/gi, "elaichi"],
  [/\bcinnamon\b/gi, "dalchini"],
  [/\bcloves?\b/gi, "laung"],
  [/\bstar anise\b/gi, "chakri phool"],
  [/\bbay leaves?\b/gi, "tej patta"],
  [/\basafoetida\b/gi, "hing"],
  [/\bcurry leaves?\b/gi, "curry patta"],
  [/\bsaffron\b/gi, "kesar"],
  [/\bgaram masala\b/gi, "garam masala"],
  [/\bchaat masala\b/gi, "chaat masala"],
  [/\bamchur\b/gi, "amchur"],
  [/\bdried mango powder\b/gi, "amchur"],
  [/\bmace\b/gi, "javitri"],
  [/\bnutmeg\b/gi, "jaiphal"],
  [/\bfennel seeds?\b/gi, "saunf"],
  [/\bcarom seeds?\b/gi, "ajwain"],
  [/\bnigella seeds?\b/gi, "kalonji"],
  [/\bpoppy seeds?\b/gi, "khus khus"],
  [/\bcumin powder\b/gi, "jeera powder"],
  [/\bblack salt\b/gi, "kala namak"],
  [/\brock salt\b/gi, "sendha namak"],
  [/\bsalt\b/gi, "namak"],
  [/\bwhite sugar\b/gi, "safed cheeni"],
  [/\bbrown sugar\b/gi, "brown cheeni"],
  [/\bpowdered sugar\b/gi, "pisi cheeni"],
  [/\bsugar\b/gi, "cheeni"],
  [/\bjaggery\b/gi, "gur"],
  [/\bhoney\b/gi, "shahad"],
  [/\blemon juice\b/gi, "nimbu ka ras"],
  [/\blime juice\b/gi, "nimbu ka ras"],
  [/\blemons?\b/gi, "nimbu"],
  [/\bwater\b/gi, "paani"],
  [/\bcoconut\b/gi, "nariyal"],
  [/\btamarind\b/gi, "imli"],
  [/\bvinegar\b/gi, "sirka"],
  [/\burad dal\b/gi, "urad dal"],
  [/\bchana dal\b/gi, "chana dal"],
  [/\bmoong dal\b/gi, "moong dal"],
  [/\btoor dal\b/gi, "toor dal"],
  [/\bkabuli chana\b/gi, "kabuli chana"],
  [/\blentils\b/gi, "dal"],
  [/\bchickpeas?\b/gi, "chhole"],
  [/\bkidney beans\b/gi, "rajma"],
  [/\brajma\b/gi, "rajma"],
  [/\bmoong\b/gi, "moong"],
  [/\bchicken\b/gi, "murga"],
  [/\bmutton\b/gi, "gosht"],
  [/\blamb\b/gi, "gosht"],
  [/\bfish\b/gi, "machli"],
  [/\bprawns?\b/gi, "jheenga"],
  [/\bshrimp\b/gi, "jheenga"],
  [/\bcrab\b/gi, "kekda"],
  [/\beggs?\b/gi, "anda"],
  [/\bsemolina\b/gi, "sooji"],
  [/\brava\b/gi, "sooji"],
  [/\bflattened rice\b/gi, "poha"],
  [/\bpuffed rice\b/gi, "murmure"],
  [/\bbread crumbs\b/gi, "bread ke tukde"],
  [/\bcornmeal\b/gi, "makki ka atta"],
  [/\bsweet corn\b/gi, "meethi makkai"],
  [/\bcorn\b/gi, "makkai"],
  [/\bvermicelli\b/gi, "seviyan"],
  [/\bbaking soda\b/gi, "meetha soda"],
  [/\btomato paste\b/gi, "tamatar paste"],
  [/\btomato puree\b/gi, "tamatar puree"],
  [/\bcashews?\b/gi, "kaju"],
  [/\balmonds?\b/gi, "badam"],
  [/\bpistachios?\b/gi, "pista"],
  [/\braisins?\b/gi, "kishmish"],
  [/\bpeanuts?\b/gi, "moongfali"],
  [/\bsesame seeds?\b/gi, "til"],
  [/\bwalnut\b/gi, "akhrot"],
  [/\bdate\b/gi, "khajoor"],
  [/\bfig\b/gi, "anjeer"],
  [/\bdried fruit\b/gi, "sukha meva"],
  [/\brose water\b/gi, "gulab jal"],
  [/\brose syrup\b/gi, "gulab sharbat"],
  [/\bsoda water\b/gi, "soda paani"],
  [/\bgreen tea\b/gi, "green chai"],
  [/\btea\b/gi, "chai"],
  [/\bice\b/gi, "barf"],
  [/\bradish\b/gi, "mooli"],
  [/\bturnip\b/gi, "shalgam"],
  [/\bbeetroot\b/gi, "chukandar"],
  [/\bcucumber\b/gi, "kheera"],
  [/\bpumpkin\b/gi, "kaddu"],
  [/\bmushroom\b/gi, "mushroom"],
  [/\bcelery\b/gi, "ajwain ka patta"],
  [/\btulsi\b/gi, "tulsi"],
  [/\bbasil\b/gi, "tulsi"],
  [/\bbesan\b/gi, "besan"],

  // Cooking instructions — longer phrases first
  [/\bpressure[- ]cook\b/gi, "cooker mein pakao"],
  [/\bdeep[- ]fry\b/gi, "deep fry karo"],
  [/\bshallow fry\b/gi, "thode tel mein talo"],
  [/\bstir[- ]fry\b/gi, "kadhai mein fry karo"],
  [/\bpan[- ]fry\b/gi, "kadhai mein fry karo"],
  [/\btawa[- ]fry\b/gi, "tawa par fry karo"],
  [/\bdouble[- ]boil\b/gi, "double boiler mein garam karo"],
  [/\bdry roast\b/gi, "sukha bhuno"],
  [/\bchar[- ]grill\b/gi, "angaar par seko"],
  [/\bheat the oil\b/gi, "tel garam karo"],
  [/\bheat oil\b/gi, "tel garam karo"],
  [/\bbring to (?:a )?boil\b/gi, "ubaal aane do"],
  [/\breduce heat\b/gi, "aanch kam karo"],
  [/\bincrease heat\b/gi, "aanch badhaao"],
  [/\bcool completely\b/gi, "bilkul thanda karo"],
  [/\blet it cool\b/gi, "thanda hone do"],
  [/\bmix well\b/gi, "achhe se mix karo"],
  [/\bheat\b/gi, "garam karo"],
  [/\bsoaked\b/gi, "bhiga hua"],
  [/\bsoak\b/gi, "bhigo do"],
  [/\bgrind\b/gi, "pees lo"],
  [/\bblend\b/gi, "blend karo"],
  [/\bfermented\b/gi, "khameer uthi hui"],
  [/\bferment\b/gi, "khameer uthne do"],
  [/\bknead well\b/gi, "achhe se goondo"],
  [/\bknead into a dough\b/gi, "atta goondo"],
  [/\bknead\b/gi, "goondo"],
  [/\bboiled\b/gi, "ubla hua"],
  [/\bboil\b/gi, "ubalo"],
  [/\bsimmer\b/gi, "dhimi aanch par pakao"],
  [/\bfried\b/gi, "fry kiya hua"],
  [/\bfry\b/gi, "fry karo"],
  [/\bsaut[eé]\b/gi, "saute karo"],
  [/\broasted\b/gi, "bhuney hue"],
  [/\broast\b/gi, "bhuno"],
  [/\btoast\b/gi, "toast karo"],
  [/\bbake\b/gi, "bake karo"],
  [/\bsteamed\b/gi, "bhap mein paka hua"],
  [/\bsteam\b/gi, "bhap mein pakao"],
  [/\bgrill\b/gi, "grill karo"],
  [/\bbroil\b/gi, "upar se seko"],
  [/\bsmoke\b/gi, "dhuan do"],
  [/\btandoor\b/gi, "tandoor mein pakao"],
  [/\bcooked\b/gi, "paka hua"],
  [/\bcook\b/gi, "pakao"],
  [/\bmash\b/gi, "masal do"],
  [/\bcrush\b/gi, "kuchal do"],
  [/\bpound\b/gi, "koot lo"],
  [/\btemper\b/gi, "tadka lagao"],
  [/\bcaramelize\b/gi, "brown karo"],
  [/\bsear\b/gi, "tej aanch par seko"],
  [/\bshape\b/gi, "shape do"],
  [/\blayer\b/gi, "layer lagao"],
  [/\bstuff\b/gi, "bhar do"],
  [/\bfill\b/gi, "bhar do"],
  [/\bwrap\b/gi, "lapet lo"],
  [/\bseal\b/gi, "band karo"],
  [/\bstir\b/gi, "hilao"],
  [/\bmix\b/gi, "mix karo"],
  [/\badd\b/gi, "dalo"],
  [/\bpour\b/gi, "daalo"],
  [/\bsprinkle\b/gi, "chidko"],
  [/\bchopped\b/gi, "kata hua"],
  [/\bchop\b/gi, "kaat lo"],
  [/\bsliced\b/gi, "slice kiya hua"],
  [/\bslice\b/gi, "slice karo"],
  [/\bgrated\b/gi, "kada hua"],
  [/\bgrate\b/gi, "kado lo"],
  [/\bpeeled\b/gi, "chheela hua"],
  [/\bpeel\b/gi, "chheel lo"],
  [/\bdrain\b/gi, "paani nikaalo"],
  [/\bwash\b/gi, "dho lo"],
  [/\brinse\b/gi, "dho lo"],
  [/\bmarinated\b/gi, "marinate kiya hua"],
  [/\bmarinate\b/gi, "marinate karo"],
  [/\bgarnish\b/gi, "garnish karo"],
  [/\bserve\b/gi, "serve karo"],
  [/\bcover\b/gi, "dhak do"],
  [/\bcool\b/gi, "thanda karo"],
  [/\bset aside\b/gi, "alag rakh do"],
  [/\bstrain\b/gi, "chhaan lo"],
  [/\bfilter\b/gi, "chhaano"],
  [/\bsieve\b/gi, "chhaani se chhan lo"],
  [/\bremove\b/gi, "nikaalo"],
  [/\brolled\b/gi, "bela hua"],
  [/\broll\b/gi, "bel lo"],
  [/\bspread\b/gi, "failao"],
  [/\bfold\b/gi, "mod lo"],
  [/\bpress\b/gi, "dabaao"],
  [/\bwhisk\b/gi, "phento"],
  [/\bbeat\b/gi, "phento"],
  [/\btoss\b/gi, "uchhal kar mix karo"],
  [/\bflip\b/gi, "ulto"],
  [/\bturn\b/gi, "palto"],
  [/\bsqueeze\b/gi, "nichod lo"],
  [/\bextract\b/gi, "nikaal lo"],
  [/\bdissolve\b/gi, "ghol do"],
  [/\bdilute\b/gi, "paani mila do"],
  [/\brefrigerate\b/gi, "fridge mein rakh do"],
  [/\bfreeze\b/gi, "freeze karo"],
  [/\breduce\b/gi, "gaaadha karo"],
  [/\bthicken\b/gi, "gaaadha karo"],
  [/\bproof\b/gi, "rise hone do"],
  [/\brest\b/gi, "rest karne do"],

  // Common phrases — longer first
  [/\buntil golden brown\b/gi, "sone ke rang tak"],
  [/\buntil golden\b/gi, "sone ke rang tak"],
  [/\buntil tender\b/gi, "naram hone tak"],
  [/\buntil soft\b/gi, "naram hone tak"],
  [/\buntil fragrant\b/gi, "khusboo aane tak"],
  [/\buntil done\b/gi, "pakne tak"],
  [/\buntil thick\b/gi, "gaadha hone tak"],
  [/\buntil completely cooked\b/gi, "poora pakne tak"],
  [/\buntil water evaporates\b/gi, "paani sukh jaane tak"],
  [/\buntil oil separates\b/gi, "tel alag hone tak"],
  [/\bover medium heat\b/gi, "madhyam aanch par"],
  [/\bwith a lid\b/gi, "dhakkan ke saath"],
  [/\bwithout lid\b/gi, "bina dhakkan ke"],
  [/\bin a blender\b/gi, "mixer mein"],
  [/\bin a food processor\b/gi, "grinder mein"],
  [/\bin a pan\b/gi, "kadhai mein"],
  [/\bin a pot\b/gi, "pateli mein"],
  [/\bin a bowl\b/gi, "bowl mein"],
  [/\bon a tawa\b/gi, "tawa par"],
  [/\bin batches\b/gi, "thodi thodi maat mein"],
  [/\bone by one\b/gi, "ek ek karke"],
  [/\bfor a few seconds\b/gi, "kuch second ke liye"],
  [/\bfor a minute\b/gi, "ek minute ke liye"],
  [/\bhigh heat\b/gi, "tej aanch"],
  [/\bmedium heat\b/gi, "madhyam aanch"],
  [/\blow heat\b/gi, "dhimi aanch"],
  [/\bovernight\b/gi, "raat bhar ke liye"],
  [/\bmeanwhile\b/gi, "tab tak"],
  [/\bfinally\b/gi, "aakhir mein"],
  [/\bfirst\b/gi, "pehle"],
  [/\bthen\b/gi, "phir"],
  [/\boptional\b/gi, "mann se"],
  [/\bif desired\b/gi, "chahe toh"],
  [/\baccording to taste\b/gi, "swad anusar"],
  [/\bas needed\b/gi, "zaroorat anusar"],
  [/\bapproximately\b/gi, "kareeb"],
  [/\babout\b/gi, "lagbhag"],
  [/\bexactly\b/gi, "bilkul"],
  [/\bminutes?\b/gi, "minute"],
  [/\bhours?\b/gi, "ghante"],
  [/\bseparately\b/gi, "alag alag"],
  [/\bthoroughly\b/gi, "achhe se"],
  [/\bgently\b/gi, "dheere se"],
  [/\bslowly\b/gi, "dheere dheere"],
  [/\bimmediately\b/gi, "turant"],
  [/\bfinely\b/gi, "bareek"],
  [/\broughly\b/gi, "mota mota"],
  [/\bcoarsely\b/gi, "darreda"],
  [/\bgolden color\b/gi, "sone ka rang"],
  [/\bdeep golden\b/gi, "gahra sona rang"],
  [/\blight brown\b/gi, "halka brown"],

  // Descriptors
  [/\bfresh\b/gi, "taaza"],
  [/\bdry\b/gi, "sukha"],
  [/\braw\b/gi, "kaccha"],
  [/\bripe\b/gi, "pakka"],
  [/\bthick\b/gi, "gaaadha"],
  [/\bthin\b/gi, "patla"],
  [/\bsmooth\b/gi, "smooth"],
  [/\bcrispy\b/gi, "kurkura"],
  [/\bcrunchy\b/gi, "kurkura"],
  [/\bsoft\b/gi, "naram"],
  [/\bspicy\b/gi, "teekha"],
  [/\bmild\b/gi, "halka"],
  [/\btangy\b/gi, "khatta"],
  [/\bsweet\b/gi, "meetha"],
  [/\bsalty\b/gi, "namkeen"],
  [/\bbitter\b/gi, "kadwa"],
  [/\bhot\b/gi, "garam"],
  [/\bwarm\b/gi, "gunguna"],
  [/\blarge\b/gi, "bada"],
  [/\bsmall\b/gi, "chota"],
  [/\bmedium\b/gi, "madhyam"],
  [/\bbubbles?\b/gi, "budbude"],
  [/\bfoam\b/gi, "jhag"],
  [/\bsteam\b/gi, "bhap"],
];

export function toHinglish(text: string): string {
  let result = text;
  for (const [pattern, replacement] of REPLACEMENTS) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

export function toHinglishList(items: string[]): string[] {
  return items.map(toHinglish);
}
