/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RatingComment {
  'id' : bigint,
  'recipeId' : bigint,
  'authorName' : string,
  'comment' : string,
  'stars' : bigint,
  'timestamp' : bigint,
}
export interface Recipe {
  'id' : bigint,
  'owner' : Principal,
  'calories' : [] | [bigint],
  'name' : string,
  'chefTips' : [] | [Array<string>],
  'cookTime' : string,
  'description' : string,
  'instructions' : Array<string>,
  'imageUrl' : string,
  'servingSize' : string,
  'prepTime' : string,
  'category' : string,
  'rating' : number,
  'isVeg' : boolean,
  'videoUrl' : [] | [string],
  'ingredients' : Array<string>,
}
export interface RecipeInput {
  'calories' : [] | [bigint],
  'name' : string,
  'chefTips' : [] | [Array<string>],
  'cookTime' : string,
  'description' : string,
  'instructions' : Array<string>,
  'imageUrl' : string,
  'servingSize' : string,
  'prepTime' : string,
  'category' : string,
  'rating' : number,
  'isVeg' : boolean,
  'videoUrl' : [] | [string],
  'ingredients' : Array<string>,
}
export type SessionId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRecipe' : ActorMethod<[RecipeInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteRecipe' : ActorMethod<[bigint, RecipeInput], boolean>,
  /**
   * / Returns count of unique sessions active within the last 5 minutes
   * / No authorization required - public metric
   */
  'getActiveUsers' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRatings' : ActorMethod<[bigint], Array<RatingComment>>,
  'getRecipes' : ActorMethod<[], Array<Recipe>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSeeded' : ActorMethod<[], boolean>,
  'getRecipeCount' : ActorMethod<[], bigint>,
  'forceReseed' : ActorMethod<[Array<RecipeInput>], undefined>,
  /**
   * / Updates timestamp to current time
   * / No authorization required - allows tracking of all visitors including guests
   */
  'pingUser' : ActorMethod<[SessionId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedRecipes' : ActorMethod<[Array<RecipeInput>], undefined>,
  'submitRating' : ActorMethod<[bigint, bigint, string, string], bigint>,
  'updateRecipe' : ActorMethod<[bigint, RecipeInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];